# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches:
      - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  create_database:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Checkout Repository
        run: git rev-parse --abbrev-ref HEAD
      
      - name: Install MongoDB Tools
        run: | 
          sudo apt update
          sudo apt install -y wget gnupg2
          sudo wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
          sudo echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
          sudo apt update
          sudo apt install -y mongodb-org-tools
          
      - name: Load Fixtures
        run: |
          set -e
          DUMP=$( cd ./fixtures/dump/smartrisk; pwd -P )
          echo -e "Loading fixtures in database \n\n"
          mongorestore $DUMP --uri ${{ secrets.DATABASE_URI }} --db smartrisk --drop
          echo -e "\n\n FINISHED LOADING FIXTURES!"
